// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// proj_trans_cpp
List proj_trans_cpp(Rcpp::CharacterVector TARGET, Rcpp::DoubleVector X, Rcpp::DoubleVector Y, Rcpp::DoubleVector Z, Rcpp::LogicalVector INV);
RcppExport SEXP _PROJ_proj_trans_cpp(SEXP TARGETSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP INVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type TARGET(TARGETSEXP);
    Rcpp::traits::input_parameter< Rcpp::DoubleVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::DoubleVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::DoubleVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type INV(INVSEXP);
    rcpp_result_gen = Rcpp::wrap(proj_trans_cpp(TARGET, X, Y, Z, INV));
    return rcpp_result_gen;
END_RCPP
}
