# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PROJ trans
#'
#' Coordinate transform in forward or inverse mode
#'
#'
#' t is set to 0 internally
#' https://proj4.org/development/quickstart.html
#'
#' @export
#' @param TARGET target projection
#' @param X x coordinate
#' @param Y y coordinate
#' @param Z z coordinate
#' @param INV forward or inverse projection (default forward = FALSE)
#' @return list of transformed x, y, z
#' @examples
#' dst<- "+proj=laea +datum=WGS84 +lon_0=1"
#' proj_trans(dst, 0, 0, 0, FALSE)
#' proj_trans(dst, -111318.1, 0, 0, TRUE)
proj_trans <- function(TARGET, X, Y, Z, INV) {
    .Call(`_PROJ_proj_trans`, TARGET, X, Y, Z, INV)
}

