# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proj_trans_cpp <- function(TARGET, X, Y, Z, INV) {
    .Call(`_PROJ_proj_trans_cpp`, TARGET, X, Y, Z, INV)
}

